export const FETCH_FORECAST_DATA_REQUEST = 'FETCH_FORECAST_DATA_REQUEST'
export const FETCH_FORECAST_DATA_SUCCESS = 'FETCH_FORECAST_DATA_SUCCESS'
export const FETCH_FORECAST_DATA_ERROR = 'FETCH_FORECAST_DATA_ERROR'